/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentLeaderboard {
  export type AgentStatsStruct = {
    agentAddress: AddressLike;
    name: string;
    totalSignals: BigNumberish;
    winningSignals: BigNumberish;
    totalProfitUSD: BigNumberish;
    totalGasUSD: BigNumberish;
    lastUpdated: BigNumberish;
    isActive: boolean;
  };

  export type AgentStatsStructOutput = [
    agentAddress: string,
    name: string,
    totalSignals: bigint,
    winningSignals: bigint,
    totalProfitUSD: bigint,
    totalGasUSD: bigint,
    lastUpdated: bigint,
    isActive: boolean
  ] & {
    agentAddress: string;
    name: string;
    totalSignals: bigint;
    winningSignals: bigint;
    totalProfitUSD: bigint;
    totalGasUSD: bigint;
    lastUpdated: bigint;
    isActive: boolean;
  };
}

export interface AgentLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentStats"
      | "getLeaderboard"
      | "getRank"
      | "getWinRate"
      | "registerAgent"
      | "registeredAgents"
      | "updateStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentRegistered" | "StatsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStats",
    values: [AddressLike, boolean, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agentStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getWinRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStats",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agent: AddressLike, name: string];
  export type OutputTuple = [agent: string, name: string];
  export interface OutputObject {
    agent: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    newTotalProfit: BigNumberish,
    winRate: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    newTotalProfit: bigint,
    winRate: bigint
  ];
  export interface OutputObject {
    agent: string;
    newTotalProfit: bigint;
    winRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): AgentLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: AgentLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        agentAddress: string;
        name: string;
        totalSignals: bigint;
        winningSignals: bigint;
        totalProfitUSD: bigint;
        totalGasUSD: bigint;
        lastUpdated: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [],
    [AgentLeaderboard.AgentStatsStructOutput[]],
    "view"
  >;

  getRank: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getWinRate: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  registerAgent: TypedContractMethod<[name: string], [void], "nonpayable">;

  registeredAgents: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  updateStats: TypedContractMethod<
    [
      agent: AddressLike,
      won: boolean,
      profitUSD: BigNumberish,
      gasUSD: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        agentAddress: string;
        name: string;
        totalSignals: bigint;
        winningSignals: bigint;
        totalProfitUSD: bigint;
        totalGasUSD: bigint;
        lastUpdated: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [],
    [AgentLeaderboard.AgentStatsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRank"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWinRate"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredAgents"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "updateStats"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      won: boolean,
      profitUSD: BigNumberish,
      gasUSD: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StatsUpdated"
  ): TypedContractEvent<
    StatsUpdatedEvent.InputTuple,
    StatsUpdatedEvent.OutputTuple,
    StatsUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "StatsUpdated(address,int256,uint256)": TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;
    StatsUpdated: TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;
  };
}
