/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AgentLeaderboard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentLeaderboard__factory>;
    getContractFactory(
      name: "NexusVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NexusVault__factory>;
    getContractFactory(
      name: "SignalRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignalRegistry__factory>;

    getContractAt(
      name: "AgentLeaderboard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentLeaderboard>;
    getContractAt(
      name: "NexusVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NexusVault>;
    getContractAt(
      name: "SignalRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignalRegistry>;

    deployContract(
      name: "AgentLeaderboard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentLeaderboard>;
    deployContract(
      name: "NexusVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusVault>;
    deployContract(
      name: "SignalRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignalRegistry>;

    deployContract(
      name: "AgentLeaderboard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentLeaderboard>;
    deployContract(
      name: "NexusVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusVault>;
    deployContract(
      name: "SignalRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignalRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
