/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SignalRegistry {
  export type SignalStruct = {
    id: BytesLike;
    publisher: AddressLike;
    strategyId: string;
    poolAddress: AddressLike;
    direction: BigNumberish;
    expectedProfitBps: BigNumberish;
    confidence: BigNumberish;
    timestamp: BigNumberish;
    executed: boolean;
    actualProfitUSD: BigNumberish;
  };

  export type SignalStructOutput = [
    id: string,
    publisher: string,
    strategyId: string,
    poolAddress: string,
    direction: bigint,
    expectedProfitBps: bigint,
    confidence: bigint,
    timestamp: bigint,
    executed: boolean,
    actualProfitUSD: bigint
  ] & {
    id: string;
    publisher: string;
    strategyId: string;
    poolAddress: string;
    direction: bigint;
    expectedProfitBps: bigint;
    confidence: bigint;
    timestamp: bigint;
    executed: boolean;
    actualProfitUSD: bigint;
  };
}

export interface SignalRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSignal"
      | "getSignalCount"
      | "getSignalsByPublisher"
      | "markExecuted"
      | "publishSignal"
      | "signalIds"
      | "signals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SignalExecuted" | "SignalPublished"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getSignal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSignalsByPublisher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExecuted",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publishSignal",
    values: [
      BytesLike,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "signalIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "signals", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getSignal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSignalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignalsByPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signalIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signals", data: BytesLike): Result;
}

export namespace SignalExecutedEvent {
  export type InputTuple = [id: BytesLike, actualProfitUSD: BigNumberish];
  export type OutputTuple = [id: string, actualProfitUSD: bigint];
  export interface OutputObject {
    id: string;
    actualProfitUSD: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalPublishedEvent {
  export type InputTuple = [
    id: BytesLike,
    publisher: AddressLike,
    strategyId: string
  ];
  export type OutputTuple = [id: string, publisher: string, strategyId: string];
  export interface OutputObject {
    id: string;
    publisher: string;
    strategyId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SignalRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SignalRegistry;
  waitForDeployment(): Promise<this>;

  interface: SignalRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSignal: TypedContractMethod<
    [id: BytesLike],
    [SignalRegistry.SignalStructOutput],
    "view"
  >;

  getSignalCount: TypedContractMethod<[], [bigint], "view">;

  getSignalsByPublisher: TypedContractMethod<
    [publisher: AddressLike],
    [string[]],
    "view"
  >;

  markExecuted: TypedContractMethod<
    [id: BytesLike, actualProfitUSD: BigNumberish],
    [void],
    "nonpayable"
  >;

  publishSignal: TypedContractMethod<
    [
      id: BytesLike,
      strategyId: string,
      pool: AddressLike,
      direction: BigNumberish,
      expectedProfitBps: BigNumberish,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  signalIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  signals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        publisher: string;
        strategyId: string;
        poolAddress: string;
        direction: bigint;
        expectedProfitBps: bigint;
        confidence: bigint;
        timestamp: bigint;
        executed: boolean;
        actualProfitUSD: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSignal"
  ): TypedContractMethod<
    [id: BytesLike],
    [SignalRegistry.SignalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSignalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSignalsByPublisher"
  ): TypedContractMethod<[publisher: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "markExecuted"
  ): TypedContractMethod<
    [id: BytesLike, actualProfitUSD: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishSignal"
  ): TypedContractMethod<
    [
      id: BytesLike,
      strategyId: string,
      pool: AddressLike,
      direction: BigNumberish,
      expectedProfitBps: BigNumberish,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signalIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "signals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        publisher: string;
        strategyId: string;
        poolAddress: string;
        direction: bigint;
        expectedProfitBps: bigint;
        confidence: bigint;
        timestamp: bigint;
        executed: boolean;
        actualProfitUSD: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "SignalExecuted"
  ): TypedContractEvent<
    SignalExecutedEvent.InputTuple,
    SignalExecutedEvent.OutputTuple,
    SignalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SignalPublished"
  ): TypedContractEvent<
    SignalPublishedEvent.InputTuple,
    SignalPublishedEvent.OutputTuple,
    SignalPublishedEvent.OutputObject
  >;

  filters: {
    "SignalExecuted(bytes32,int256)": TypedContractEvent<
      SignalExecutedEvent.InputTuple,
      SignalExecutedEvent.OutputTuple,
      SignalExecutedEvent.OutputObject
    >;
    SignalExecuted: TypedContractEvent<
      SignalExecutedEvent.InputTuple,
      SignalExecutedEvent.OutputTuple,
      SignalExecutedEvent.OutputObject
    >;

    "SignalPublished(bytes32,address,string)": TypedContractEvent<
      SignalPublishedEvent.InputTuple,
      SignalPublishedEvent.OutputTuple,
      SignalPublishedEvent.OutputObject
    >;
    SignalPublished: TypedContractEvent<
      SignalPublishedEvent.InputTuple,
      SignalPublishedEvent.OutputTuple,
      SignalPublishedEvent.OutputObject
    >;
  };
}
